In [1]:
import numpy as np

In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [5]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [11]:
a_centered = np.subtract (a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [12]:
a1 = a_centered[:, 0]
a2 = a_centered[:, 1]
a_centered_sp = np.dot(a1, a2)
a_centered_sp

8.0

In [13]:
N = a.shape[0]
N

5

In [14]:
my_cov = a_centered_sp/(N-1)
my_cov

2.0

In [15]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

In [16]:
import pandas as pd

In [17]:
authors = pd.DataFrame ({'author_id' : [1, 2, 3],
                        'author_name' : ['Тургенев', 'Чехов', 'Островский']},
                       columns = ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [20]:
books = pd.DataFrame ({'author_id' : [1, 1, 1, 2, 2, 3, 3],
                    'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                                     'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                       'price' : [450, 300, 350, 500, 450, 370, 290]},
                     columns = ['author_id', 'book_title', 'price'])
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290